name: build
on:
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u germey -p ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
    - name: Build the Docker Image
      run: |
        docker build -t germey/scrapyd .
    - name: Push the Docker Image
      run: docker push germey/scrapyd
